export const TILE_SIZE = 32;
export const FONT_SIZE = 24;
export const FONT_FAMILY = "monospace";

export const FEET_PER_TILE = 5;

export const WALK_SPEED_CELLS_PER_SECOND = 1;
export const RUN_SPEED_MULTIPLIER = 2;

export const WALK_SPEED = TILE_SIZE * WALK_SPEED_CELLS_PER_SECOND;
export const RUN_SPEED = WALK_SPEED * RUN_SPEED_MULTIPLIER;

export const DODGE_DISTANCE_FEET = 5;
export const DODGE_DISTANCE_PIXELS = (DODGE_DISTANCE_FEET / FEET_PER_TILE) * TILE_SIZE;

export const ENEMY_SPEED = TILE_SIZE * 0.75;
export const ENEMY_FLEE_SPEED = TILE_SIZE * 1.15;

export const ATTACK_RANGE_FEET = 7.5;
export const ATTACK_RANGE_PIXELS = (ATTACK_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;

export const PLAYER_ATTACK_DAMAGE = 3;
export const ENEMY_ATTACK_DAMAGE = 2;

export const PLAYER_ATTACK_COOLDOWN = 3;
export const ENEMY_ATTACK_COOLDOWN = 3;
export const ENEMY_ACTION_CAST_TIME = 1.5;
export const MERCHANT_THEFT_CHECK_INTERVAL = 6;
export const MERCHANT_THEFT_NOTICE_DC = 15;

export const SPELL_CAST_TIME = 3;
export const SPELL_COOLDOWN = 3;

export const HEALING_WORD_RANGE_FEET = 60;
export const HEALING_WORD_RANGE_PIXELS = (HEALING_WORD_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;


export const ENEMY_SPELL_COOLDOWN = 8;
export const MAGIC_MISSILE_RANGE_FEET = 120;
export const MAGIC_MISSILE_RANGE_PIXELS = (MAGIC_MISSILE_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const MAGIC_MISSILE_RANGE_TILES = MAGIC_MISSILE_RANGE_FEET / FEET_PER_TILE;
export const ENEMY_MAGIC_MISSILE_RANGE_TILES = MAGIC_MISSILE_RANGE_TILES;
export const ENEMY_MAGIC_MISSILE_RANGE_PIXELS = MAGIC_MISSILE_RANGE_PIXELS;

export const MAGIC_MISSILE_COUNT = 3;
export const MAGIC_MISSILE_DAMAGE = 2;
export const MAGIC_MISSILE_CHAR = "x";
export const MAGIC_MISSILE_SIZE_MULTIPLIER = 0.5;
export const MAGIC_MISSILE_RADIUS = TILE_SIZE * 0.35 * MAGIC_MISSILE_SIZE_MULTIPLIER;
export const MAGIC_MISSILE_SPAWN_DISTANCE = TILE_SIZE * 0.65;
export const MAGIC_MISSILE_INITIAL_SPEED = TILE_SIZE * 0.8;
export const MAGIC_MISSILE_MAX_SPEED = TILE_SIZE * 5.5;
export const MAGIC_MISSILE_ACCELERATION = TILE_SIZE * 6;
export const MAGIC_MISSILE_TURN_SPEED = Math.PI * 1.8;
export const MAGIC_MISSILE_LIFETIME = 5;

export const BURNING_HANDS_RANGE_FEET = 15;
export const BURNING_HANDS_RANGE_PIXELS = (BURNING_HANDS_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const BURNING_HANDS_CONE_ANGLE_RADIANS = 2 * Math.atan(0.5);
export const BURNING_HANDS_PROJECTILE_COUNT = 15;
export const BURNING_HANDS_DAMAGE_DICE = 3;
export const BURNING_HANDS_DAMAGE_DIE = 6;
export const BURNING_HANDS_CHAR = "x";
export const BURNING_HANDS_RADIUS = TILE_SIZE * 0.24;
export const BURNING_HANDS_SPEED = TILE_SIZE * 4.4;
export const BURNING_HANDS_EMISSION_INTERVAL = 0.75;
export const BURNING_HANDS_LIFETIME = 1.05;


export const FIREBALL_RANGE_FEET = 150;
export const FIREBALL_RANGE_PIXELS = (FIREBALL_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const FIREBALL_RADIUS_FEET = 10;
export const FIREBALL_RADIUS_PIXELS = (FIREBALL_RADIUS_FEET / FEET_PER_TILE) * TILE_SIZE;
export const FIREBALL_DAMAGE_DICE = 8;
export const FIREBALL_DAMAGE_DIE = 6;
export const FIREBALL_DAMAGE_DELAY = 1;
export const FIREBALL_ORB_SPEED = TILE_SIZE * 8.5;
export const FIREBALL_ORB_RADIUS = TILE_SIZE * 0.22;
export const FIREBALL_SPARK_COUNT = 48;
export const FIREBALL_SPARK_LIFETIME = 0.75;

export const VORTEX_WARP_RANGE_FEET = 90;
export const VORTEX_WARP_RANGE_PIXELS = (VORTEX_WARP_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const COUNTERSPELL_RANGE_FEET = 60;
export const COUNTERSPELL_RANGE_PIXELS = (COUNTERSPELL_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;

export const FIRE_BOLT_RANGE_FEET = 120;
export const FIRE_BOLT_RANGE_PIXELS = (FIRE_BOLT_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const FIRE_BOLT_DAMAGE_DICE = 4;
export const FIRE_BOLT_DAMAGE_DIE = 10;
export const FIRE_BOLT_PROJECTILE_CHAR = "x";
export const FIRE_BOLT_PROJECTILE_COLOR = "#ff4a00";
export const FIRE_BOLT_PROJECTILE_RADIUS = TILE_SIZE * 0.16;
export const FIRE_BOLT_PROJECTILE_DRAW_SIZE = TILE_SIZE * 0.55;
export const FIRE_BOLT_PROJECTILE_SPEED = TILE_SIZE * 9.5;
export const FIRE_BOLT_PROJECTILE_LIFETIME = 3.2;

export const CHROMATIC_ORB_RANGE_FEET = 90;
export const CHROMATIC_ORB_RANGE_PIXELS = (CHROMATIC_ORB_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const CHROMATIC_ORB_DAMAGE_DICE = 3;
export const CHROMATIC_ORB_DAMAGE_DIE = 8;
export const CHROMATIC_ORB_PROJECTILE_CHAR = "x";
export const CHROMATIC_ORB_PROJECTILE_COLOR = "#66d9ff";
export const CHROMATIC_ORB_PROJECTILE_RADIUS = TILE_SIZE * 0.22;
export const CHROMATIC_ORB_PROJECTILE_DRAW_SIZE = TILE_SIZE * 0.7;
export const CHROMATIC_ORB_INITIAL_SPEED = TILE_SIZE * 1.2;
export const CHROMATIC_ORB_MAX_SPEED = TILE_SIZE * 6.2;
export const CHROMATIC_ORB_ACCELERATION = TILE_SIZE * 5.2;
export const CHROMATIC_ORB_TURN_SPEED = Math.PI * 1.35;
export const CHROMATIC_ORB_PROJECTILE_LIFETIME = 4.2;

export const SHIELD_DURATION = 6;

export const WALL_OF_FORCE_RANGE_FEET = 60;
export const WALL_OF_FORCE_RANGE_PIXELS = (WALL_OF_FORCE_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const WALL_OF_FORCE_DURATION = 8;
export const WALL_OF_FORCE_LENGTH_TILES = 3;
export const WALL_OF_FORCE_PUSH_FEET = 5;
export const WALL_OF_FORCE_PUSH_PIXELS = (WALL_OF_FORCE_PUSH_FEET / FEET_PER_TILE) * TILE_SIZE;

export const ENEMY_DETECTION_RANGE_TILES = 6;
export const ENEMY_DETECTION_RANGE_PIXELS = ENEMY_DETECTION_RANGE_TILES * TILE_SIZE;

export const ENEMY_LOW_HP_PERCENT = 0.35;


export const BOW_ATTACK_RANGE_FEET = 80;
export const BOW_ATTACK_RANGE_PIXELS = (BOW_ATTACK_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;

export const ARROW_INITIAL_QUANTITY = 20;
export const ARROW_PROJECTILE_CHAR = "x";
export const ARROW_PROJECTILE_COLOR = "#d8c27a";
export const ARROW_PROJECTILE_RADIUS = TILE_SIZE * 0.12;
export const ARROW_PROJECTILE_DRAW_SIZE = TILE_SIZE * 0.5;
export const ARROW_PROJECTILE_SPEED = TILE_SIZE * 9;
export const ARROW_PROJECTILE_LIFETIME = 2.5;

export const LARGE_ROOM_STRUCTURE_MIN_FLOOR_TILES = 48;
export const LARGE_ROOM_STRUCTURE_MAX_SEGMENTS = 3;
export const LARGE_ROOM_STRUCTURE_MIN_LENGTH = 2;
export const LARGE_ROOM_STRUCTURE_MAX_LENGTH = 4;

export const POTION_OF_HEALING_DICE = 2;
export const POTION_OF_HEALING_DIE = 4;
export const POTION_OF_HEALING_BONUS = 2;

export const MISTY_STEP_RANGE_FEET = 30;
export const MISTY_STEP_RANGE_PIXELS = (MISTY_STEP_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;

export const DISINTEGRATE_SCROLL_RANGE_FEET = 7.5;
export const DISINTEGRATE_SCROLL_RANGE_PIXELS = (DISINTEGRATE_SCROLL_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const DISINTEGRATE_SCROLL_DAMAGE_DICE = 10;
export const DISINTEGRATE_SCROLL_DAMAGE_DIE = 6;
export const DISINTEGRATE_SCROLL_DAMAGE_BONUS = 40;

export const FORCECAGE_SCROLL_RANGE_FEET = 100;
export const FORCECAGE_SCROLL_RANGE_PIXELS = (FORCECAGE_SCROLL_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const FORCECAGE_SCROLL_DURATION = 12;
export const FORCECAGE_SCROLL_SIZE_TILES = 3;

export const ITEM_PICKUP_RANGE_PIXELS = TILE_SIZE * 0.65;
export const TORCH_INTERACTION_RANGE_FEET = 5;
export const TORCH_INTERACTION_RANGE_PIXELS = (TORCH_INTERACTION_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const TORCH_PLACE_RANGE_FEET = 5;
export const TORCH_PLACE_RANGE_PIXELS = (TORCH_PLACE_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const RANDOM_LOOT_CHANCE = 0.65;
export const RANDOM_LOOT_MAX_PER_ROOM = 3;
export const CHEST_SPAWN_CHANCE = 0.34;
export const CHEST_LOOT_MIN_ITEMS = 2;
export const CHEST_LOOT_MAX_ITEMS = 5;
export const CHEST_INTERACTION_RANGE_FEET = 5;
export const CHEST_INTERACTION_RANGE_PIXELS = (CHEST_INTERACTION_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;


export const TORCH_LIGHT_RADIUS_FEET = 25;
export const TORCH_LIGHT_RADIUS_PIXELS = (TORCH_LIGHT_RADIUS_FEET / FEET_PER_TILE) * TILE_SIZE;
export const PLAYER_LIGHT_RADIUS_FEET = 15;
export const PLAYER_LIGHT_RADIUS_PIXELS = (PLAYER_LIGHT_RADIUS_FEET / FEET_PER_TILE) * TILE_SIZE;
export const ROOM_TORCH_CHANCE = 1;
export const ROOM_TORCH_MAX_COUNT = 3;

export const MERCHANT_ROOM_CHANCE = 0.14;
export const MERCHANT_INTERACTION_RANGE_FEET = 7.5;
export const MERCHANT_INTERACTION_RANGE_PIXELS = (MERCHANT_INTERACTION_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const MERCHANT_HIRE_COST = 50;
export const MERCHANT_ALLY_LOW_HP_PERCENT = 0.35;
export const MERCHANT_ALLY_MIN_ENEMY_DISTANCE_FEET = 15;
export const MERCHANT_ALLY_MIN_ENEMY_DISTANCE_PIXELS = (MERCHANT_ALLY_MIN_ENEMY_DISTANCE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const MERCHANT_ALLY_FRONT_DISTANCE_FEET = 10;
export const MERCHANT_ALLY_FRONT_DISTANCE_PIXELS = (MERCHANT_ALLY_FRONT_DISTANCE_FEET / FEET_PER_TILE) * TILE_SIZE;

export const ENEMY_SEPARATION_RANGE_PIXELS = TILE_SIZE * 1.25;
export const ENEMY_SEPARATION_STRENGTH = 0.9;
export const ENEMY_PATH_RECALC_INTERVAL = 0.35;
export const ENEMY_PATH_NODE_REACHED_DISTANCE = TILE_SIZE * 0.22;
export const ENEMY_LOST_TARGET_DISTANCE = TILE_SIZE * 0.55;
export const ENEMY_CASTER_MIN_DISTANCE_FEET = 20;
export const ENEMY_CASTER_MIN_DISTANCE_PIXELS = (ENEMY_CASTER_MIN_DISTANCE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const ENEMY_CASTER_PREFERRED_DISTANCE_FEET = 35;
export const ENEMY_CASTER_PREFERRED_DISTANCE_PIXELS = (ENEMY_CASTER_PREFERRED_DISTANCE_FEET / FEET_PER_TILE) * TILE_SIZE;

export const DRAGON_BOSS_ROOM_MIN_FLOOR_TILES = 36;
export const DRAGON_BOSS_SPAWN_CHANCE = 0.18;
export const CENTIPEDE_SPAWN_CHANCE = 0.08;

export const DRAGON_BOSS_SIZE_TILES = 3;
export const DRAGON_BOSS_RADIUS = TILE_SIZE * 1.35;
export const DRAGON_BOSS_HP = 80;
export const DRAGON_BOSS_MELEE_DAMAGE = 10;
export const DRAGON_BOSS_BREATH_DAMAGE_DICE = 6;
export const DRAGON_BOSS_BREATH_DAMAGE_DIE = 6;
export const DRAGON_BOSS_BREATH_RANGE_FEET = 30;
export const DRAGON_BOSS_BREATH_RANGE_PIXELS = (DRAGON_BOSS_BREATH_RANGE_FEET / FEET_PER_TILE) * TILE_SIZE;
export const DRAGON_BOSS_BREATH_CONE_ANGLE_RADIANS = Math.PI / 2;
export const DRAGON_BOSS_BREATH_COOLDOWN = 9;
export const DRAGON_BOSS_BREATH_PROJECTILE_COUNT = 36;

export const CENTIPEDE_SEGMENT_COUNT = 12;
export const CENTIPEDE_SEGMENT_SPACING = TILE_SIZE * 0.68;
export const CENTIPEDE_TURN_SPEED = Math.PI * 0.72;
export const CENTIPEDE_SPEED = TILE_SIZE * 1.05;
export const CENTIPEDE_ATTACK_DAMAGE = 4;
